"""Generate a best-effort ``native.pyi`` stub for IDE completion.

The :class:`~sap2000py.native.NativeApi` proxy resolves everything dynamically,
so editors can't complete ``client.api.PointObj.AddCartesian(...)`` out of the
box. This run-once developer script connects to a real SAP2000 instance,
reflects over the live ``cSapModel`` object tree, and emits a permissive stub
mapping each sub-object to its methods.

Usage (with SAP2000 installed)::

    uv run python -m sap2000py._stubgen.gen_native_stubs

This is *developer tooling*, not part of the runtime. The generated stub is
intentionally permissive (``*args: Any -> Any``): it exists for discoverability,
not type safety. The typed ``model`` layer is the type-checked path.
"""

from __future__ import annotations

import keyword
from pathlib import Path
from typing import Any

_HEADER = '''"""Auto-generated by sap2000py._stubgen — do not edit by hand.

Permissive completion stub for the NativeApi dynamic proxy.
Regenerate with: uv run python -m sap2000py._stubgen.gen_native_stubs
"""
from typing import Any


'''


def _public_methods(obj: Any) -> list[str]:
    """Names on a COM object that look like callable OAPI methods."""
    names = []
    for name in dir(obj):
        if name.startswith("_") or keyword.iskeyword(name):
            continue
        try:
            attr = getattr(obj, name)
        except Exception:
            continue
        if callable(attr):
            names.append(name)
    return sorted(set(names))


def _sub_objects(model: Any) -> dict[str, Any]:
    """Map each sub-interface name (PointObj, FrameObj, ...) to its live object."""
    subs: dict[str, Any] = {}
    for name in dir(model):
        if name.startswith("_") or keyword.iskeyword(name):
            continue
        try:
            attr = getattr(model, name)
        except Exception:
            continue
        if attr is not None and not callable(attr) and not isinstance(
            attr, (int, float, str, bool, bytes, tuple, list, dict)
        ):
            subs[name] = attr
    return subs


def generate(model: Any, out_path: Path) -> Path:
    """Reflect over a live ``cSapModel`` and write a stub to ``out_path``."""
    lines = [_HEADER]
    subs = _sub_objects(model)

    for sub_name, sub_obj in sorted(subs.items()):
        cls = f"_{sub_name}Proxy"
        lines.append(f"class {cls}:")
        methods = _public_methods(sub_obj)
        if not methods:
            lines.append("    def __getattr__(self, name: str) -> Any: ...")
        for meth in methods:
            lines.append(f"    def {meth}(self, *args: Any) -> Any: ...")
        lines.append("")

    lines.append("class NativeApi:")
    lines.append("    node: Any")
    for sub_name in sorted(subs):
        lines.append(f"    {sub_name}: _{sub_name}Proxy")
    lines.append("    def __getattr__(self, name: str) -> Any: ...")
    lines.append("")

    out_path.write_text("\n".join(lines), encoding="utf-8")
    return out_path


def main() -> None:
    from sap2000py import SapClient

    client = SapClient.attach_or_launch(visible=False)
    try:
        target = Path(__file__).resolve().parent.parent / "native.pyi"
        written = generate(client.raw_model, target)
        print(f"Wrote stub: {written}")
    finally:
        client.close()


if __name__ == "__main__":
    main()
