"""Generate a best-effort ``native.pyi`` stub for IDE completion.

The :class:`~sap2000py.native.NativeApi` proxy resolves everything dynamically,
so editors can't complete ``client.api.PointObj.AddCartesian(...)`` out of the
box. This run-once developer script connects to a real SAP2000 instance,
reflects over the live ``cSapModel`` object tree, and emits a permissive stub
mapping each sub-object to its methods.

Usage (with SAP2000 installed)::

    uv run python -m sap2000py._stubgen.gen_native_stubs

This is *developer tooling*, not part of the runtime. The generated stub is
intentionally permissive (``*args: Any -> Any``): it exists for discoverability,
not type safety. The typed ``model`` layer is the type-checked path.
"""

from __future__ import annotations

import keyword
from pathlib import Path
from typing import Any

from ..gateway import _VALUE_GETTERS

_HEADER = '''"""Auto-generated by sap2000py._stubgen — do not edit by hand.

Permissive completion stub for the NativeApi dynamic proxy.
Regenerate with: uv run python -m sap2000py._stubgen.gen_native_stubs
"""
from typing import Any


'''

#: IUnknown / IDispatch plumbing comtypes exposes on every node. They are real
#: attributes but never part of the OAPI surface, so they only clutter editor
#: completion — drop them from the stub.
_COM_PLUMBING = frozenset(
    {
        "AddRef",
        "Release",
        "QueryInterface",
        "Invoke",
        "GetIDsOfNames",
        "GetTypeInfo",
        "GetTypeInfoCount",
        "from_param",
        "value",
    }
)


def _public_methods(obj: Any) -> list[str]:
    """Names on a COM object that look like callable OAPI methods."""
    names = []
    for name in dir(obj):
        if name.startswith("_") or keyword.iskeyword(name) or name in _COM_PLUMBING:
            continue
        try:
            attr = getattr(obj, name)
        except Exception:
            continue
        if callable(attr):
            names.append(name)
    return sorted(set(names))


def _sub_objects(model: Any) -> dict[str, Any]:
    """Map each sub-interface name (PointObj, FrameObj, ...) to its live object."""
    subs: dict[str, Any] = {}
    for name in dir(model):
        if name.startswith("_") or keyword.iskeyword(name):
            continue
        try:
            attr = getattr(model, name)
        except Exception:
            continue
        if name in _COM_PLUMBING:
            continue
        if (
            attr is not None
            and not callable(attr)
            and not isinstance(attr, (int, float, str, bool, bytes, tuple, list, dict))
        ):
            subs[name] = attr
    return subs


def audit_value_getters(model: Any) -> list[str]:
    """Flag bare-value getters that may be missing from the gateway allow-set.

    The SAP2000 type library can't distinguish a status-returning ``long`` from
    a value-returning ``long``, so :data:`~sap2000py.gateway._VALUE_GETTERS` is a
    *curated* set. The dominant upgrade risk is a new ``Count*`` method (every
    one is a value-getter). After a SAP2000 upgrade, run this: it walks the live
    object tree and returns any ``Count*`` / unit-getter leaf name not already
    classified, so a human can extend the set before it silently misfires.
    """
    suspects: set[str] = set()
    for sub_obj in _sub_objects(model).values():
        for meth in _public_methods(sub_obj):
            looks_like_value = meth.startswith("Count") or meth in {
                "GetDatabaseUnits",
                "GetPresentUnits",
            }
            if looks_like_value and meth not in _VALUE_GETTERS:
                suspects.add(meth)
    return sorted(suspects)


def generate(model: Any, out_path: Path) -> Path:
    """Reflect over a live ``cSapModel`` and write a stub to ``out_path``."""
    lines = [_HEADER]
    subs = _sub_objects(model)

    for sub_name, sub_obj in sorted(subs.items()):
        cls = f"_{sub_name}Proxy"
        lines.append(f"class {cls}:")
        methods = _public_methods(sub_obj)
        if not methods:
            lines.append("    def __getattr__(self, name: str) -> Any: ...")
        for meth in methods:
            lines.append(f"    def {meth}(self, *args: Any) -> Any: ...")
        lines.append("")

    lines.append("class NativeApi:")
    lines.append("    node: Any")
    # Match native.py's real constructor so the stub (which shadows the .py for
    # type checking) doesn't break internal construction in client.py.
    lines.append("    def __init__(self, gateway: Any, node: Any, path: str = ...) -> None: ...")
    for sub_name in sorted(subs):
        lines.append(f"    {sub_name}: _{sub_name}Proxy")
    lines.append("    def __getattr__(self, name: str) -> Any: ...")
    lines.append("")

    out_path.write_text("\n".join(lines), encoding="utf-8")
    return out_path


def main() -> None:
    from sap2000py import SapClient

    client = SapClient.attach_or_launch(visible=False)
    try:
        target = Path(__file__).resolve().parent.parent / "native.pyi"
        written = generate(client.raw_model, target)
        print(f"Wrote stub: {written}")
        suspects = audit_value_getters(client.raw_model)
        if suspects:
            print(
                "WARNING: bare value-getter candidates not in gateway._VALUE_GETTERS: "
                f"{suspects}. Review and add genuine value-getters, or the proxy will "
                "treat their return as a status code."
            )
        else:
            print("Value-getter allow-set audit: OK (no new candidates).")
    finally:
        client.close()


if __name__ == "__main__":
    main()
